// Code generated by protoc-gen-go. DO NOT EDIT.
// source: newsfeedpb/newsfeed.proto

package newsfeedpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Newsfeed struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Newsfeed) Reset()         { *m = Newsfeed{} }
func (m *Newsfeed) String() string { return proto.CompactTextString(m) }
func (*Newsfeed) ProtoMessage()    {}
func (*Newsfeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_d722b1f49019b149, []int{0}
}

func (m *Newsfeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Newsfeed.Unmarshal(m, b)
}
func (m *Newsfeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Newsfeed.Marshal(b, m, deterministic)
}
func (m *Newsfeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Newsfeed.Merge(m, src)
}
func (m *Newsfeed) XXX_Size() int {
	return xxx_messageInfo_Newsfeed.Size(m)
}
func (m *Newsfeed) XXX_DiscardUnknown() {
	xxx_messageInfo_Newsfeed.DiscardUnknown(m)
}

var xxx_messageInfo_Newsfeed proto.InternalMessageInfo

func (m *Newsfeed) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Newsfeed) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type NewsfeedRequest struct {
	Newsfeed             *Newsfeed `protobuf:"bytes,1,opt,name=newsfeed,proto3" json:"newsfeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewsfeedRequest) Reset()         { *m = NewsfeedRequest{} }
func (m *NewsfeedRequest) String() string { return proto.CompactTextString(m) }
func (*NewsfeedRequest) ProtoMessage()    {}
func (*NewsfeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d722b1f49019b149, []int{1}
}

func (m *NewsfeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsfeedRequest.Unmarshal(m, b)
}
func (m *NewsfeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsfeedRequest.Marshal(b, m, deterministic)
}
func (m *NewsfeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsfeedRequest.Merge(m, src)
}
func (m *NewsfeedRequest) XXX_Size() int {
	return xxx_messageInfo_NewsfeedRequest.Size(m)
}
func (m *NewsfeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsfeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewsfeedRequest proto.InternalMessageInfo

func (m *NewsfeedRequest) GetNewsfeed() *Newsfeed {
	if m != nil {
		return m.Newsfeed
	}
	return nil
}

type NewsfeedResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewsfeedResponse) Reset()         { *m = NewsfeedResponse{} }
func (m *NewsfeedResponse) String() string { return proto.CompactTextString(m) }
func (*NewsfeedResponse) ProtoMessage()    {}
func (*NewsfeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d722b1f49019b149, []int{2}
}

func (m *NewsfeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsfeedResponse.Unmarshal(m, b)
}
func (m *NewsfeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsfeedResponse.Marshal(b, m, deterministic)
}
func (m *NewsfeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsfeedResponse.Merge(m, src)
}
func (m *NewsfeedResponse) XXX_Size() int {
	return xxx_messageInfo_NewsfeedResponse.Size(m)
}
func (m *NewsfeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsfeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewsfeedResponse proto.InternalMessageInfo

func (m *NewsfeedResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Newsfeed)(nil), "newsfeed.Newsfeed")
	proto.RegisterType((*NewsfeedRequest)(nil), "newsfeed.NewsfeedRequest")
	proto.RegisterType((*NewsfeedResponse)(nil), "newsfeed.NewsfeedResponse")
}

func init() { proto.RegisterFile("newsfeedpb/newsfeed.proto", fileDescriptor_d722b1f49019b149) }

var fileDescriptor_d722b1f49019b149 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x4b, 0x2d, 0x2f,
	0x4e, 0x4b, 0x4d, 0x4d, 0x29, 0x48, 0xd2, 0x87, 0x31, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x38, 0x60, 0x7c, 0x25, 0x33, 0x2e, 0x0e, 0x3f, 0x28, 0x5b, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0xb5,
	0xa2, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x4b, 0x2c,
	0x2d, 0xc9, 0xc8, 0x2f, 0x92, 0x60, 0x02, 0x8b, 0x42, 0x79, 0x4a, 0x8e, 0x5c, 0xfc, 0x30, 0x7d,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7a, 0x5c, 0x70, 0x63, 0xc1, 0x46, 0x70, 0x1b,
	0x09, 0xe9, 0xc1, 0xed, 0x85, 0x2b, 0x46, 0x58, 0xad, 0xc5, 0x25, 0x80, 0x30, 0xa2, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x15, 0x64, 0x5d, 0x51, 0x6a, 0x71, 0x69, 0x0e, 0xcc, 0x11, 0x50, 0x9e, 0x51,
	0x18, 0xc2, 0xba, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x67, 0x24, 0x97, 0x4b, 0x62,
	0xb1, 0x08, 0xe2, 0x2a, 0x29, 0x29, 0x6c, 0x52, 0x10, 0xdb, 0x94, 0x18, 0x9c, 0x78, 0xa2, 0xb8,
	0x10, 0xa1, 0x94, 0xc4, 0x06, 0x0e, 0x1d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x56,
	0x2b, 0xaa, 0x3a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NewsfeedServiceClient is the client API for NewsfeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NewsfeedServiceClient interface {
	// Unary
	Newsfeed(ctx context.Context, in *NewsfeedRequest, opts ...grpc.CallOption) (*NewsfeedResponse, error)
}

type newsfeedServiceClient struct {
	cc *grpc.ClientConn
}

func NewNewsfeedServiceClient(cc *grpc.ClientConn) NewsfeedServiceClient {
	return &newsfeedServiceClient{cc}
}

func (c *newsfeedServiceClient) Newsfeed(ctx context.Context, in *NewsfeedRequest, opts ...grpc.CallOption) (*NewsfeedResponse, error) {
	out := new(NewsfeedResponse)
	err := c.cc.Invoke(ctx, "/newsfeed.NewsfeedService/Newsfeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsfeedServiceServer is the server API for NewsfeedService service.
type NewsfeedServiceServer interface {
	// Unary
	Newsfeed(context.Context, *NewsfeedRequest) (*NewsfeedResponse, error)
}

// UnimplementedNewsfeedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNewsfeedServiceServer struct {
}

func (*UnimplementedNewsfeedServiceServer) Newsfeed(ctx context.Context, req *NewsfeedRequest) (*NewsfeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Newsfeed not implemented")
}

func RegisterNewsfeedServiceServer(s *grpc.Server, srv NewsfeedServiceServer) {
	s.RegisterService(&_NewsfeedService_serviceDesc, srv)
}

func _NewsfeedService_Newsfeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsfeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedServiceServer).Newsfeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/newsfeed.NewsfeedService/Newsfeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedServiceServer).Newsfeed(ctx, req.(*NewsfeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NewsfeedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "newsfeed.NewsfeedService",
	HandlerType: (*NewsfeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Newsfeed",
			Handler:    _NewsfeedService_Newsfeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "newsfeedpb/newsfeed.proto",
}
